apiVersion: v1
kind: Service
metadata:
  name: mysql-cliente
spec:
  type: ClusterIP
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql-cliente