apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente
  labels:
    app: cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: client
          image: wesleyroberts/bora-praticar:1.2.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: clientedb
          envFrom:
            - configMapRef:
                name: cliente
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "128Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cliente
spec:
  selector:
    app: cliente
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cliente-lb
spec:
  selector:
    app: cliente
  type: NodePort
  ports:
    - name: cliente
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30173

