global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "api-cliente"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:80']